### ISSUE TITLE
current status

### ISSUE THREAD

**Issue by beerisgood** [BetterFirefox/BetterFirefox#1]
How is the current status?

**Comment by beerisgood** [comment]
Project alive? No commits since january

**Comment by CHEF-KOCH** [comment]
I'm closing the project now and I fully turn my back on Mozilla. If someone like to have the ownership of the project or organization - feel free to contact me via eMail. 

<details>
  <summary>The long sad story</summary>
  I had over the last 3 weeks more than 15 conferences with lots of Mozilla people and I not agree in their marketing _lies_. They make money by fooling people saying the Browser is more secure than others (it's not btw) then they copy constantly features Google already added years ago (and they got criticized for that [for no reasons]) - now they use exactly the [same marketing strategy](http://blog.mozilla.org/futurereleases/2018/04/30/a-privacy-conscious-approach-to-sponsored-content/) (again). Remember that Google ALWAYS had RLZ (that what people called 'spying' which was open source one week after the introduction. This got 'over-hyped' because it was the first Browser 'telemetry' and now such things are anyway quite common in every OS or complex software/driver product. To stay on the RLZ topic, it got never called or used when you used Chrome from the official sources (you only got the 'tag' when you downloaded a homebrew versions or an unofficial version [I'm just saying cause the Wikipedia article is wrong and misleading regarding RLZ]. I see this as unproblematically as long there options given - I guess that was the only thing what people all over the place complained about. 

So what I tried? Overall I put 600 hours if not more in discussions, feedback etc. with developers and other people involved into the entire 'Mozilla' topic and it's simply disappointing to know that marketing is now their main priority (and nope it didn't started with the 'Mr Robot scandal' [it started earlier]).

I made like 195 suggestions (on my own) what could be improved in Firefox + Thunderbird and only 10 got approved and integrated. This is more than frustrating.  I can't waste my lifetime fighting for and good products (yes I still see hope overall in their products, but we need other management) without getting anything out of it. I'm already involved in Chromium development, several private GitHub repos and other projects - this is a full time job and if you need to fight against the management with such simple thing like (one example) integrate into the installer a telemetry opt-out or such basic things then it's clear why they playing this game....

People still trying to 'fix' pointless things with configs and this is nothing but a waste of time especially if most people simply want a clean browser, so what they do they install (possible) outdated Forks or trying to mess with the config related things (some people even have no clue what such toggles really do - which I consider as possible dangerous). This is not the philosophy I want to support. I think it could be so easy, but they making it more and more complicated.
 
I'm not sure if I will give Mozilla another try I need to see, definitly not with the current managment. 
</details>

**Comment by beerisgood** [comment]
Then i share this, cause their exist inprovement for Firefox. Sad you switch to the biggest spying company Google.

https://github.com/ghacksuserjs/ghacks-user.js

**Comment by CHEF-KOCH** [comment]
1. Using configurations files is exactly for a handful of people. This should never be a goal for a Browser which claims to be 'secure'. However, this affects in general every other Browser too.
2. Marketing and configuration related things are two separate things. You can waste you lifetime trying to 'fix' broken stuff or and install 100 extensions, 1 million configuration files etc - or you go the smart way and invest this time to start-over / or use alternatives.
3. No Browser spy's not even if you login into it. This would and is against EU data privacy law. This also affects Mozilla the same way like Google. If you know better than you would be the first which comes up with some proof. Sadly, a history entry in your local Browser storage is not spying. To only name one example.
4. I never really _switched_ I'm involved in Chrome/Chromium since years. I never found evidence (cause there is none) that the Browser by itself collects data in a way which is against laws, you can tbh also compile Chrome/ium and Firefox like you want. However, Chromeium is easier cause things not often break that much like in FF - remember that FF recently changed a lot, extension api etc. If you ever compiled FF at your own you would have known. Chrome is easier to maintain (at least for me) cause less things can break cause there are no gimmicks like Hello integrated.
5. Saying that Google is evil without anything is wrong, Mozilla and Google in fact worked and still working together they even now work together with Cloudflare. I'm not sure if you aware about the complexity of this or the entire background. 

I think you missed the point that I spent more time than everyone else on this topic (as I'm aware of) and this matter, especially because I already mentioned clearly that Mozilla products aren't bad, I just said that their decisions and marketing is against my own policy and I not want to invest my time fighting against windmills. The decision I made was also not motivated cause I'm involed in these Browser bitch-fights (I don't even care) it's simply because I and Mozilla have too different opinions about the future.
